### ISSUE TITLE
Bug: Server has no valid information about required documents

### ISSUE THREAD

**Issue by jbeard4** [streetlives/streetlives-api#17]
Steps to reproduce:

On streetlives-web branch `handle-documents-info-null`, visit: http://localhost:3000/location/621cedc1-728a-47ab-91d7-53f1bf34f9f8/services/bcd2747a-7006-43b7-bfaf-251282125319/opening-hours

Set the hours. Click OK.

Server replies with 500 error:

```
{"error":"Error: Service has no valid information about required documents\n    at /Users/jbeard4/workspace/streetlives/streetlives-api/src/controllers/services.js:45:15\n    at Generator.next (<anonymous>)\n    at step (/Users/jbeard4/workspace/streetlives/streetlives-api/src/controllers/services.js:29:191)\n    at /Users/jbeard4/workspace/streetlives/streetlives-api/src/controllers/services.js:29:361\n    at <anonymous>"}
```

Might be related to the fact that `DocumentsInfo` is for this location's service is null.

<img src="http://g.recordit.co/Y5uB8x1g7I.gif">

**Comment by Rovack** [comment]
Should be fixed. See general details in [this Asana task](https://app.asana.com/0/695464422622907/875271948470576/f), and the migration script that solved this in [this commit](https://github.com/streetlives/streetlives-api/commit/60acdccf44d16c450bafea9c43611d8c7a831861).
